title: TRAUMGRÄTSCHE Regelbuch
description: Das Regelwerk des Fußball-Manager-Brettspiel TRAUMGRÄTSCHE
theme: just-the-docs

url: https://heupinho.github.io/traumgraetsche-docs/

aux_links:
  Perfect Tackling: https://www.youtube.com/watch?v=DK3aNN9dVKI
